from .task_tools import (
    create_task,
    get_task,
    list_tasks,
    update_task,
    delete_task,
    assign_task,
    unassign_task,
    change_task_status,
    create_subtask,
    list_subtasks,
    add_task_dependency,
    remove_task_dependency,
    get_task_dependencies,
    add_task_comment,
    get_task_activity,
    bulk_update_tasks,
    tool_calculate_critical_path,
    get_overdue_tasks,
)
from .volunteer_tools import (
    create_volunteer,
    get_volunteer,
    list_volunteers,
    update_volunteer,
    delete_volunteer,
    get_volunteer_tasks,
    tool_calculate_volunteer_load,
    get_overloaded_volunteers,
    suggest_task_owner,
    bulk_reassign_tasks,
)
from .event_tools import (
    create_event,
    get_event,
    list_events,
    update_event,
    delete_event,
    get_event_dashboard,
    get_event_timeline,
    get_event_budget,
    record_expense,
    update_budget_allocation,
    generate_event_plan,
)
from .meeting_tools import (
    create_meeting,
    get_meeting,
    list_meetings,
    update_meeting,
    extract_action_items,
    resolve_action_item_references,
    review_extracted_actions,
    apply_extracted_actions,
)
from .risk_tools import (
    list_risks,
    get_risk,
    detect_event_risks,
    detect_task_risks,
    explain_risk,
    suggest_risk_fix,
    resolve_risk,
    get_unowned_tasks_near_deadline,
    get_overload_risks,
    get_dependency_conflicts,
    get_missing_activity_risks,
)

# Unified inventory of all AI-callable tools
ALL_AI_TOOLS = {
    # 1. Task Tools (18)
    "create_task": create_task,
    "get_task": get_task,
    "list_tasks": list_tasks,
    "update_task": update_task,
    "delete_task": delete_task,
    "assign_task": assign_task,
    "unassign_task": unassign_task,
    "change_task_status": change_task_status,
    "create_subtask": create_subtask,
    "list_subtasks": list_subtasks,
    "add_task_dependency": add_task_dependency,
    "remove_task_dependency": remove_task_dependency,
    "get_task_dependencies": get_task_dependencies,
    "add_task_comment": add_task_comment,
    "get_task_activity": get_task_activity,
    "bulk_update_tasks": bulk_update_tasks,
    "calculate_critical_path": tool_calculate_critical_path,
    "get_overdue_tasks": get_overdue_tasks,

    # 2. Volunteer Tools (10)
    "create_volunteer": create_volunteer,
    "get_volunteer": get_volunteer,
    "list_volunteers": list_volunteers,
    "update_volunteer": update_volunteer,
    "delete_volunteer": delete_volunteer,
    "get_volunteer_tasks": get_volunteer_tasks,
    "calculate_volunteer_load": tool_calculate_volunteer_load,
    "get_overloaded_volunteers": get_overloaded_volunteers,
    "suggest_task_owner": suggest_task_owner,
    "bulk_reassign_tasks": bulk_reassign_tasks,

    # 3. Event Tools (11)
    "create_event": create_event,
    "get_event": get_event,
    "list_events": list_events,
    "update_event": update_event,
    "delete_event": delete_event,
    "get_event_dashboard": get_event_dashboard,
    "get_event_timeline": get_event_timeline,
    "get_event_budget": get_event_budget,
    "record_expense": record_expense,
    "update_budget_allocation": update_budget_allocation,
    "generate_event_plan": generate_event_plan,

    # 4. Meeting Tools (8)
    "create_meeting": create_meeting,
    "get_meeting": get_meeting,
    "list_meetings": list_meetings,
    "update_meeting": update_meeting,
    "extract_action_items": extract_action_items,
    "resolve_action_item_references": resolve_action_item_references,
    "review_extracted_actions": review_extracted_actions,
    "apply_extracted_actions": apply_extracted_actions,

    # 5. Risk Tools (11)
    "list_risks": list_risks,
    "get_risk": get_risk,
    "detect_event_risks": detect_event_risks,
    "detect_task_risks": detect_task_risks,
    "explain_risk": explain_risk,
    "suggest_risk_fix": suggest_risk_fix,
    "resolve_risk": resolve_risk,
    "get_unowned_tasks_near_deadline": get_unowned_tasks_near_deadline,
    "get_overload_risks": get_overload_risks,
    "get_dependency_conflicts": get_dependency_conflicts,
    "get_missing_activity_risks": get_missing_activity_risks,
}
